# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Scrum Kata
email: scrumkata@gmail.com
repository: huserben/scrum-kata
description: >- # this means to ignore newlines until "baseurl:"
  Scrum Kata is a hobby project by professional Scrum Masters [Benji Huser](https://github.com/huserben) and [Henadz Kavaliou](https://github.com/henadzkavaliou).
  While preparing for the PSM-III assessment we tried to answer questions around Scrum in a practice group and discussed them together afterwards.
  In the complex domain there is rarely a single answer for a problem, and in the discussions we had we learned about the different angles all those potential problems could be tackled.

  We also realized that we came up with many questions that we'd like to share with the community so others can use them for their assessment preparation or just to work on their Scrum Master skills.

  Our current product goal is to provide a question library for all to use. In future this might change - if you have good ideas let us know!
baseurl: "/scrum-kata"
url: "https://huserben.github.io"
github_username:  huserben
permalink: pretty

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed

search_enabled: true

aux_links:
  "Random Question":
    - "//huserben.github.io/scrum-kata/random.html"
  "Download Questions":
    - "//huserben.github.io/scrum-kata/download.html"
  "Feedback":
    - "//github.com/huserben/scrum-kata/issues/new?"

last_edit_timestamp: true 
last_edit_time_format: "%b %e %Y at %I:%M %p" 

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/huserben/scrum-kata"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

google_analytics: G-MQDZVVFZ2G

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
