name: Create PRs for added issues

on:
  issues:
    types: 
      - opened

jobs:
  createPr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Create Questions Index
        working-directory: Scripts
        run: |
          python ./create_question.py "${{ github.event.issue.title }}" "${{ github.event.issue.body }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          delete-branch: true
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: "${{ github.event.issue.title }}"
          body: "#${{ github.event.issue.number }}"