name: Create PRs for added issues

on:
  issues:
    types: 
      - opened
      - edited
      - reopened

jobs:
  createPr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python 3.8
        uses: actions/setup-python@v6
        with:
          python-version: 3.8

      - name: Create Questions Index
        working-directory: Scripts
        run: |
          python ./create_question.py "${{ github.event.issue.title }}" "${{ github.event.issue.body }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
          delete-branch: true
          commit-message: "${{ github.event.issue.title }}"
          committer: ${{ github.event.issue.user.login }} <${{ github.event.issue.user.login }}@github.com>
          author: ${{ github.event.issue.user.login }} <${{ github.event.issue.user.login }}@users.noreply.github.com>
          title: "Add Question: ${{ github.event.issue.title }}"
          branch: "Issue_${{ github.event.issue.number }}"
          body: |
            Reference Issue: #${{ github.event.issue.number }}
