name: Check Spelling of Questions

on:
  pull_request:
    branches:
      - main

jobs:
  getchangedfiles:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Get changed files in the _questions folder
        id: changed-files
        uses: tj-actions/changed-files@v29.0.7
        with:
          files: |
            _questions/**

      - name: Put Changed Files in Matrix
        id: set-matrix
        run: |

          MATRIX="{\"include\":[" 

          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
            MATRIX="${MATRIX}{\"fileName\":\"${file}\"}, "
          done

          MATRIX="${MATRIX::-2}]}"
          echo "${MATRIX}"
          echo "::set-output name=matrix::${MATRIX}"

  spellcheck:
    runs-on: ubuntu-latest
    needs: getchangedfiles
    strategy:
      matrix:
        value: ${{ fromJSON(needs.getchangedfiles.outputs.matrix) }}

    steps:
      - run: |
          echo "${{ matrix.value }}"